 let taskcreator = require("./taskCreation")
 let taskmanager = require("./taskManagement")

 let homeWork = new taskcreator.task('finish home work', '1.daniels trask 2.exrcises from book', '12.5.2020')
 let task1 = new taskcreator.task('task1', '1.daniels trask 2.exrcises from book', '12.5.2020')
 let task2 = new taskcreator.task('task2', '1.daniels trask 2.exrcises from book', '12.5.2020')
 let task3 = new taskcreator.task('task3', '1.daniels trask 2.exrcises from book', '12.5.2020')
 taskmanager.addTask(homeWork)
 taskmanager.addTask(task1)
 taskmanager.addTask(task2)
 taskmanager.addTask(task3)
 let index1 = taskmanager.finishtask(task2.taskName)
 console.log(index1)
 console.log(taskmanager.unfinishedTasks)
 console.log(taskmanager.finshedTasks)